### ISSUE TITLE
Debug Transaction on Archive Node

### ISSUE THREAD

**Issue by henry-hz** [fuseio/fuse-network#170]
Dear Fusers!
I need to debug a transaction using the archive node and [tx2uml](https://github.com/naddison36/tx2uml) , but seems that the archive is limiting it. `debug_traceTransaction` is active, but seems that it's pointing to a localhost.

```
ARCHIVE_NODE_URL=https://explorer-node.fuse.io

~/audit/liquity-contracts/tx master ❯ tx2uml 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b -v                                                                                                   10:55:23
  tx2uml verbose on +0ms
  tx2uml About to generate tx calls for 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b +2ms
  tx2uml Using Geth client. +0ms
  tx2uml About to get tx details and receipt from chain for 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b +0ms
  tx2uml Got tx details and receipt for 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b +965ms
  tx2uml About to get transaction trace for 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b +0ms
  axios POST https://explorer-node.fuse.io +0ms
  axios 200 OK (POST https://explorer-node.fuse.io) +117ms
Error: Failed to get transaction trace for tx hash 0xeaf760d80c15a25670fffe0586313615053c740a5970121b622dc177ee0c8a3b from url https://explorer-node.fuse.io.
    at GethClient.getTransactionTrace (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/clients/GethClient.js:49:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ... 4 lines matching cause stack trace ...
    at async main (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/tx2uml.js:133:5) {
  [cause]: Error: debug_traceTransaction found but the containing module is disabled for the url 'http://0.0.0.0:8545', consider adding module in JsonRpcConfig.AdditionalRpcUrls for additional url, or to JsonRpcConfig.EnabledModules for default url
      at GethClient.getTransactionTrace (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/clients/GethClient.js:34:23)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async TransactionManager.getTraces (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/transaction.js:37:37)
      at async generateCallDiagram (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/callDiagram.js:32:41)
      at async Command.<anonymous> (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/tx2uml.js:68:9)
      at async Command.parseAsync (/Users/henry/.npm-packages/lib/node_modules/tx2uml/node_modules/commander/lib/command.js:1092:5)
      at async main (/Users/henry/.npm-packages/lib/node_modules/tx2uml/lib/tx2uml.js:133:5)
}
```

**Comment by gr8h** [comment]
trace_transaction is supported.
debug has a bit destructive commands, if needed you could sync a local node for this purpose.
